# Generated by Django 5.2 on 2025-05-03 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreCoffe', '0005_usuario_is_active_usuario_is_admin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaccion',
        ),
    ]
